// inertia-react/inertia/pages/errors/not_found.tsx
import MarketingLayout from '~/layouts/marketing'
import { type ReactElement } from 'react'

export default function NotFound() {
  return (
    <div className="home">
      <article className="prose-card">
        <div className="pc-top">
          <span className="pc-status mono tag" style={{ color: 'var(--subtle)' }}>
            <span className="dot" /> 404
          </span>
        </div>
        <div className="pc-lead">
          <span>Not found.</span>
          <em>That route hasn&apos;t been built yet.</em>
        </div>
        <p className="pc-para">
          The page you tried to reach doesn&apos;t exist. Check the URL or head back home.
        </p>
      </article>
    </div>
  )
}

NotFound.layout = (page: ReactElement) => <MarketingLayout>{page}</MarketingLayout>

// inertia-vue/inertia/pages/errors/not_found.vue
<script setup lang="ts">
import MarketingLayout from '~/layouts/marketing.vue'
</script>

<template>
  <MarketingLayout>
    <div class="home">
      <article class="prose-card">
        <div class="pc-top">
          <span class="pc-status mono tag" :style="{ color: 'var(--subtle)' }">
            <span class="dot" /> 404
          </span>
        </div>
        <div class="pc-lead">Not found.</div>
        <p class="pc-para">
          The page you tried to reach doesn't exist. Check the URL or head back home.
        </p>
      </article>
    </div>
  </MarketingLayout>
</template>
