// inertia-react/inertia/pages/errors/server_error.tsx
import MarketingLayout from '~/layouts/marketing'
import { type ReactElement } from 'react'

export default function ServerError() {
  return (
    <div className="home">
      <article className="prose-card">
        <div className="pc-top">
          <span className="pc-status mono tag" style={{ color: '#c0392b' }}>
            <span className="dot" /> 500
          </span>
        </div>
        <div className="pc-lead">
          <span>Something broke.</span>
          <em>The server hit an unexpected error.</em>
        </div>
        <p className="pc-para">
          Try again in a moment. If the problem persists, check the server logs for the underlying
          exception.
        </p>
      </article>
    </div>
  )
}

ServerError.layout = (page: ReactElement) => <MarketingLayout>{page}</MarketingLayout>

// inertia-vue/inertia/pages/errors/server_error.vue
<script setup lang="ts">
import MarketingLayout from '~/layouts/marketing.vue'
</script>

<template>
  <MarketingLayout>
    <div class="home">
      <article class="prose-card">
        <div class="pc-top">
          <span class="pc-status mono tag" :style="{ color: '#c0392b' }">
            <span class="dot" /> 500
          </span>
        </div>
        <div class="pc-lead">Something broke.</div>
        <p class="pc-para">
          Try again in a moment. If the problem persists, check the server logs for the underlying
          exception.
        </p>
      </article>
    </div>
  </MarketingLayout>
</template>
