// inertia-react/inertia/components/theme_toggle.tsx
import { Moon, Sun } from 'lucide-react'
import { useState } from 'react'
import { usePage } from '@inertiajs/react'
import { type Data } from '@generated/data'

const COOKIE = 'kit_theme'
const ONE_YEAR = 60 * 60 * 24 * 365

export default function ThemeToggle() {
  const page = usePage<Data.SharedProps>()
  const [theme, setTheme] = useState<'light' | 'dark'>(page.props.preferences?.theme ?? 'light')

  const toggle = () => {
    const next = theme === 'dark' ? 'light' : 'dark'
    setTheme(next)
    document.documentElement.setAttribute('data-theme', next)
    document.cookie = `${COOKIE}=${next}; path=/; max-age=${ONE_YEAR}; samesite=lax`
  }

  const isDark = theme === 'dark'
  return (
    <button
      type="button"
      className="iconbtn"
      onClick={toggle}
      aria-label={isDark ? 'Switch to light theme' : 'Switch to dark theme'}
      title={isDark ? 'Switch to light theme' : 'Switch to dark theme'}
    >
      <Sun size={16} className={`themetoggle__icon ${isDark ? 'themetoggle__icon--on' : ''}`} />
      <Moon size={16} className={`themetoggle__icon ${isDark ? '' : 'themetoggle__icon--on'}`} />
    </button>
  )
}

// inertia-vue/inertia/components/theme_toggle.vue
<script setup lang="ts">
import { ref } from 'vue'
import { usePage } from '@inertiajs/vue3'
import { Moon, Sun } from 'lucide-vue-next'
import type { Data } from '@generated/data'

const COOKIE = 'kit_theme'
const ONE_YEAR = 60 * 60 * 24 * 365

const page = usePage<Data.SharedProps>()
const theme = ref<'light' | 'dark'>(page.props.preferences?.theme ?? 'light')

function toggle() {
  const next = theme.value === 'dark' ? 'light' : 'dark'
  theme.value = next
  document.documentElement.setAttribute('data-theme', next)
  document.cookie = `${COOKIE}=${next}; path=/; max-age=${ONE_YEAR}; samesite=lax`
}
</script>

<template>
  <button
    type="button"
    class="iconbtn"
    :aria-label="theme === 'dark' ? 'Switch to light theme' : 'Switch to dark theme'"
    :title="theme === 'dark' ? 'Switch to light theme' : 'Switch to dark theme'"
    @click="toggle"
  >
    <Sun
      :size="16"
      class="themetoggle__icon"
      :class="{ 'themetoggle__icon--on': theme === 'dark' }"
    />
    <Moon
      :size="16"
      class="themetoggle__icon"
      :class="{ 'themetoggle__icon--on': theme !== 'dark' }"
    />
  </button>
</template>
