// inertia-react/inertia/layouts/auth.tsx
import { type ReactNode } from 'react'
import Logo from '~/components/logo'
import FlashToasts from '~/components/flash_toasts'
import ThemeToggle from '~/components/theme_toggle'

export default function AuthLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <div className="auth">
        <div className="auth__form-col">
          <Logo size={28} />
          <div className="auth__form-wrap">{children}</div>
          <div style={{ height: 20 }} />
        </div>

        <aside className="auth__aside">
          <div className="auth__aside-top">
            <ThemeToggle />
          </div>

          <p className="auth__quote">
            Auth, kept intentionally minimal so you can build it your way.
          </p>

          <div>
            <div className="pitch__t">Looking for production-ready auth?</div>
            <p className="pitch__p">
              Check out Kit components, production-ready full-stack components from the creator of
              AdonisJS.
            </p>
            <a
              className="il pitch__a"
              href="https://plus.adonisjs.com/kit"
              target="_blank"
              rel="noreferrer"
            >
              Explore Kit components →
            </a>
          </div>
        </aside>
      </div>
      <FlashToasts />
    </>
  )
}

// inertia-vue/inertia/layouts/auth.vue
<script setup lang="ts">
import Logo from '~/components/logo.vue'
import FlashToasts from '~/components/flash_toasts.vue'
import ThemeToggle from '~/components/theme_toggle.vue'
</script>

<template>
  <div class="auth">
    <div class="auth__form-col">
      <Logo :size="28" />
      <div class="auth__form-wrap">
        <slot />
      </div>
      <div :style="{ height: '20px' }" />
    </div>

    <aside class="auth__aside">
      <div class="auth__aside-top">
        <ThemeToggle />
      </div>

      <p class="auth__quote">Auth, kept intentionally minimal so you can build it your way.</p>

      <div>
        <div class="pitch__t">Looking for production-ready auth?</div>
        <p class="pitch__p">
          Check out Kit components, production-ready full-stack components from the creator of
          AdonisJS.
        </p>
        <a
          class="il pitch__a"
          href="https://plus.adonisjs.com/kit"
          target="_blank"
          rel="noreferrer"
        >
          Explore Kit components →
        </a>
      </div>
    </aside>
  </div>
  <FlashToasts />
</template>
